params:
  siteName: "mEDRA"
  tagline: "Multilingual European DOI Registration Agency"
  email: "[ediser@ediser.it](mailto:ediser@ediser.it)"
  phone: "(+39) 0289280801"
  address: "Corso di Porta Romana, 108 – 20122 Milano, Italia"
