backend:
  name: github
  repo: Ediser-mEDRA/mEDRA-website
  branch: develop
  base_url: https://www-medra-dev.medra.org
  auth_endpoint: auth
  #causes all commits to be “squashed” into a single commit when the pull request is merged
  squash_merges: true

local_backend: true
display_url: https://ediser-medra.github.io/mEDRA-website

logo:
  src: https://ediser-medra.github.io/mEDRA-website/images/medra-without-text-logo-removebg-preview.png
  show_in_header: true
  
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

i18n:
  structure: multiple_folders
  locales: [de, en, it]
  default_locale: en
  
collections:
  - name: public-area-about-medra
    label: "About mEDRA"
    folder: "content/public-area/about-medra"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "hidden", required: false, i18n: true },
       { label: "Last Updated By", name: "author", widget: "hidden", required: false, i18n: true },
    ]

  - name: public-area-new-users
    label: "New Users"
    folder: "content/public-area/new-users"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]
  
  - name: public-area-technical-documentation
    label: "Technical Documentation"
    folder: "content/public-area/technical-documentation"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]

  - name: reserved-area-account-management
    label: "Account Management 🔐"
    folder: "content/reserved/account-management"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]

  - name: reserved-area-doi-registration
    label: "DOI Registration 🔐"
    folder: "content/reserved/doi-registration"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]
  
  - name: reserved-area-doi-url-update
    label: "DOI URL Update 🔐"
    folder: "content/reserved/doi-url-update"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]

  - name: reserved-area-doi-crawlable-url-service
    label: "DOI Crawlable URL Service 🔐"
    folder: "content/reserved/doi-crawlable-url-service"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]

  - name: reserved-area-citations-registration
    label: "Citations Registration 🔐"
    folder: "content/reserved/citations-registration"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]

  - name: reserved-area-query-upload
    label: "Query Upload 🔐"
    folder: "content/reserved/query-upload"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]

  - name: reserved-area-drs-basic-registration
    label: "DRS Basic Registration 🔐"
    folder: "content/reserved/drs-basic-registration"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]
  
  - name: reserved-area-monitoring-registration
    label: "Monitoring Registration 🔐"
    folder: "content/reserved/monitoring-registration"
    create: true
    i18n: true
    fields: [
       { label: "Title", name: "title", widget: "string", i18n: true },
       { label: "Description", name: "description", widget: "string", required: false, i18n: true },
       { label: "Weight", name: "weight", widget: "number", i18n: duplicate },
       { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: true },
       { label: "Date", name: "date", widget: "datetime", required: false, default: "{{now}}", i18n: true },
       { label: "Content", name: "body", widget: "markdown", i18n: true },
       { label: "Author", name: "author", widget: "string", required: true, i18n: true },
    ]
